[package]
name = "n2t_emu"
version = "0.1.0"
authors = ["Abhay Nayar <abhaynayar@gmail.com>"]
edition = "2018"

[dependencies]
time = "*"
log = "0.4.8"

env_logger = "0.7.1"
pixels = "0.2.0"
winit = "0.22.0"
winit_input_helper = "0.6.0"
